### PR TITLE
Clarify sample images

### PR DESCRIPTION
**Pull request by etarena**
Comments have been added to indicate to users the images to use within individual tutorials.

### CODE REVIEW

**Comment by etarena** [comment]
@ctrueden @bnorthan  take a look.  in the comments - i just indicated the images to use within each tutorial... hopefully it's more clear now for the users.

**Comment by hinerm** [comment]
@bnorthan I asked @ctrueden about this and he mentioned that he was going to let you look at this one. would you mind taking a quick look that you agree with these comments? Thanks! :octopus:

**Comment by etarena** [comment]
Thanks @bnorthan  -- I'll make those changes ...

**Comment by etarena** [comment]
@bnorthan -- changes have been made.  take a look...

**Comment by bnorthan** [comment]
Looks great.  @etarena is there anything else you want to add??  If not I can merge it.

**Comment by etarena** [comment]
@bnorthan nope - we're all good.

**Comment by etarena** [comment]
@bnorthan done.

**Comment by bnorthan** [comment]
Awesome!

**Comment by hinerm** [comment]
@bnorthan @etarena so I was the one who said each commit message should have some identifier differentiating where the change was located. This is actually valuable information as it allows someone to glance at the commit messages and know (or at least have a suggestion) the location of the changes int hat commit. If the messages were undesirable or confusing, I would have made them more specific instead of less.

[This article](http://chris.beams.io/posts/git-commit/) is a great one on Git commit messages, since it links back to practical examples - like [Linux](https://github.com/torvalds/linux/commit/67dfae0cd72fec5cd158b6e5fb1647b7dbe0834c) and [Git](https://github.com/git/git/commit/2e0f3663f59f71c857034c65078d956ee1350679) - which illustrate meticulous documentation in their commits messages and titles.

There are always other ways of discovering this information, but a commit message is typically your "first line of defense" for conveying information to other developers... so if we use duplicate messages we are missing an opportunity for communication.

**Comment by etarena** [comment]
@hinerm oops.

**Comment by ctrueden** [comment]
I agree with @hinerm!

Although in this case, these changes were so small they probably could have just been a single commit with message "Document recommended images" to avoid the whole issue. :wink:

**Comment by hinerm** [comment]
@etarena it's fine. I did not give a good explanation of why I was telling you to put those prefixes there in the first place.

>"Document recommended images" to avoid the whole issue.

This is true... but more commits = more complex rebase = more fun!

**Comment by etarena** [comment]
@hinerm ...  now that you said that - I remember having that 'specific' conversation on 'specificity'...  lesson double-learned.  ;)  (at least i got the hang of intro-to-rebasing!)

**Comment by bnorthan** [comment]
@hinerm, @ctrueden, @etarena 

OK that makes sense.  Sounds like duplicate commit messages should be avoided after all.

**Pull request merged**
