### PR TITLE
Add measure examples

### PR DESCRIPTION
**Pull request by bnorthan**
Add an example showing how to label then measure the size and intensity
of objects using ops and imglib2.

### CODE REVIEW

**Comment by bnorthan** [comment]
This example is based on gitter advice from @dietzc.

**Comment by hadim** [comment]
Nice example !

FYI, look at this similar script : http://imagej.net/ImageJ2_Python_Scripts#Retrieve_objects.2Fparticles_from_a_mask

Few comments :

- you refer to the "Crop Confocal Series tutorial" but it doesn't run anymore because of modification in the ops namespace (`ops.transform().crop` instead of `ops.image().crop`). Could you modify the "Crop Confocal Series tutorial" script ?

-To avoid issue like that in the future, do you mind adding a test for both scripts ? It's very easy to do. Look at https://github.com/imagej/imagej-scripting/blob/master/src/test/java/net/imagej/scripting/ImageJ2ScriptTest.java#L30 for an example.

**Comment by bnorthan** [comment]
@hadim I am pretty sure @hinerm fixed the [Crop Confocal Series](https://github.com/imagej/imagej-scripting/blob/master/src/main/resources/script_templates/Tutorials/Crop_Confocal_Series.py) a while ago.  I also went through a bunch of the scripts and fixed a few things just before Christmas.  

Are all the changes we are making being distributed??  My Fiji has imagej-scripting-0.4.0.   Do you think we should update the main build to use 0.4.1?  Do you know how to do this??  If not we should ping the experts and figure it out, so we can make sure all the new scripts and updates are making it into the build.

**Comment by ctrueden** [comment]
@bnorthan I am happy to cut a new release of `imagej-scripting`, and update `pom-scijava` and `imagej` to use it, whenever you say the word.

**Comment by hadim** [comment]
There is 4 easy PRs to review. Maybe we could take care of that @bnorthan and once it's done @ctrueden can cut a new release.

What do you think ?

**Comment by bnorthan** [comment]
Yes, we should be able to close the open pull request by early next week.

**Comment by bnorthan** [comment]
@hadim @ctrueden I merged three of the open pull requests and closed and deleted the other, which was redundant.  I still need to add some tests for my scripts (the testing framework is very easy to work with @hadim , good work).  I should be finished that Monday, and we should be ready to cut a new release.

**Pull request merged**
