### PR TITLE
Add a test framework for scripts

### PR DESCRIPTION
**Pull request by hadim**
See https://github.com/imagej/imagej-scripting/pull/16 for the record.

### CODE REVIEW

**Comment by hadim** [comment]
LGTM for me.

**Comment by bnorthan** [comment]
@hadim when I build with 'mvn' from the command line, several tests produce the following message (though the tests appear to actually pass)

[ERROR] Cannot create plugin: class='net.imagej.table.process.ResultsPostprocessor', priority=-9999.0, enabled=true, pluginType=PostprocessorPlugin
java.lang.IllegalArgumentException: Required service is missing: org.scijava.ui.UIService

**Comment by hadim** [comment]
The last commit should remove the error message.

**Comment by bnorthan** [comment]
Hi @hadim it now works for me.  Great!.  It looks good overall.  Did you run autoformat <kbd>shift</kbd><kbd>ctrl</kbd><kbd>f</kbd>??  Looked like there were a couple misalignments in some of the files.  Otherwise it looks good and I would be happy to merge this.

**Comment by hadim** [comment]
I run auto-format on all the files. Fell free to merge when you want.

**Pull request merged**
